name: Call delete merged branchs

on: 
  workflow_call:
    inputs:
      from_branch_name:
        description: "from branch name"
        type: string
        required: true
    secrets:
      CI_TOKEN:
        description: "CI_TOKEN to run whole jobs"
        required: true

jobs:
  get-delete-target-branchs:
    name: Get delete target branchs
    runs-on: ubuntu-latest
    steps:
      - name: Set up git user
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Checkout branch
        run: |
          git fetch --all
          git checkout ${{ inputs.from_branch_name }}

      - name: Get delete target branchs
        id: get_delete_target_branchs
        run: |
          delete_target_branchs=$(git branch -r --merged | grep -v "origin/main\|origin/dev\|origin/HEAD" | sed 's/origin\///')
          echo "delete_target_branchs = $delete_target_branchs"
          echo "${{ inputs.from_branch_name }}_delete_target_branchs=$delete_target_branchs" >> $GITHUB_ENV 
      
      - name: Delete Merged Branches
        run: |
          for branch in ${{ env.merged_branches }}; do
              git push origin --delete $branch
          done