name: Call delete merged branchs

on: 
  workflow_call:
    inputs:
      from_branch_name:
        description: "from branch name"
        type: string
        required: true
    secrets:
      CI_TOKEN:
        description: "CI_TOKEN to run whole jobs"
        required: true

jobs:
  get-delete-target-branchs:
    name: Get delete target branchs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_TOKEN }}

      - name: Checkout branch
        run: |
          git fetch --all
          git checkout ${{ inputs.from_branch_name }}

      - name: 'Debug: List all branches'
        run: |
          echo "Listing all branches:"
          git branch -a

      - name: 'Debug: List merged branches'
        run: |
          echo "Listing merged branches:"
          git branch -r --merged

      - name: Get delete target branchs
        id: get_delete_target_branchs
        run: |
          delete_target_branchs=$(git branch -r --merged | grep -v "origin/main\|origin/dev\|origin/HEAD" | sed 's/origin\///'  | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')
          echo "find delete_target_branchs=$delete_target_branchs"
          echo "delete_target_branchs=$delete_target_branchs" >> $GITHUB_ENV
  
      - name: 'Debug: Print delete target branches'
        run: |
          echo "Delete target branches: ${{ env.delete_target_branchs }}"

      
      - name: Delete Merged Branches
        if: ${{ env.delete_target_branchs != '' }}
        run: |
          IFS=$'\n' read -r -d '' -a branches <<< "${{ env.delete_target_branchs }}"
          for branch in "${branches[@]}"; do
            echo "Deleting branch: $branch"
            git push origin --delete "$branch" || echo "Failed to delete branch: $branch"
          done