name: Delete Merged Branches
permissions:
  issues: write
  contents: write

on:
  workflow_dispatch:

jobs:
  delete_merged_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_TOKEN }}
      - name: Set up git user
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
  
      - name: Delete Merged Branches
        uses: crs-k/stale-branches@v5.0.0