name: DP Delete Branches

on: workflow_dispatch

jobs:
  set_up:
    runs-on: ubuntu-latest
    steps:
      - name: Set up git user
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
  
  delete_main_merged_branchs:
    needs: set_up
    uses: ./.github/workflows/call_delete_merged_branchs.yml
    with:
      from_branch_name: "main"
    secrets:
      CI_TOKEN: ${{ secrets.CI_TOKEN }}

  delete_dev_merged_branchs:
    needs: delete_main_merged_branchs
    uses: ./.github/workflows/call_delete_merged_branchs.yml
    with:
      from_branch_name: "dev"
    secrets:
      CI_TOKEN: ${{ secrets.CI_TOKEN }}      

