name: DP Delete Branches
permissions:
  issues: write
  contents: write

on:
  workflow_dispatch:

jobs:
  delete_merged_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_TOKEN }}
      - name: Set up git user
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Ceckout branch
        run: |
          git fetch --all
          git checkout dev

      - name: Fetch all branches
        run: |
          git fetch --all
      
      - name: Get Merged Branches
        id: get_merged_branches
        run: |
          merged_branches=$(git branch -r --merged | grep -v "origin/main\|origin/dev\|origin/HEAD" | sed 's/origin\///')
          echo "merged_branches = $merged_branches"
          echo "merged_branches=$merged_branches" >> $GITHUB_ENV
    
      - name: Delete Merged Branches
        run: |
          for branch in ${{ env.merged_branches }}; do
            git push origin --delete $branch
          done